# codemagic.yaml
workflows:
  android-debug:
    name: Android Debug Build
    environment:
      vars:
        PACKAGE_NAME: "com.example.amir_bistro_orders" # عدّلها حسب package name عندك

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true

    scripts:
      - name: Install Flutter
        script: |
          flutter --version
          flutter pub get

      - name: Build Debug APK
        script: |
          flutter build apk --debug \
            --dart-define=PACKAGE_NAME=$PACKAGE_NAME

    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk

    publishing:
      email:
        recipients:
          - mo.fadel1096@gmail.com
        notify:
          success: true
          failure: true
